version: '3'

services:
    build:
        build: ./build2
        volumes:
            - data_volume:/app/HW12/App42PaaS-Java-MySQL-Sample/target
           # - data_volume:/home/app
        networks:
            net:
                ipv4_address: 192.168.0.10            
    
    db:
        image: mysql:8.0
        ports:
            - '3306:3306'
        expose:
            - '3306'
        environment:
            MYSQL_DATABASE: 'Appdb'
            MYSQL_USER: 'App'
            MYSQL_PASSWORD: 'App'
            MYSQL_ROOT_PASSWORD: 'App'
        volumes:
            - ./sqldata:/var/lib/mysql
        networks:
            net:
                ipv4_address: 192.168.0.11

    web:
        image: tomcat:8.0
        ports:
            - '8080:8080'
        volumes:
            - data_volume:/usr/local/tomcat/webapps
        networks:
            net:
                ipv4_address: 192.168.0.12            

volumes:
    data_volume:

networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24        