version: "3"

services:
    build:
        build: ./build
        volumes:
            - data_volume:/home/app
    
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'Appdb'
            MYSQL_USER: 'App'
            MYSQL_PASSWORD: 'App'
            MYSQL_ROOT_PASSWORD: 'App'
        volumes:
            - ./sqldata:/var/lib/mysql

    web:
        image: tomcat:7.0
        ports:
            - "8080:8080"
        volumes:
            - data_volume:/usr/local/tomcat/webapps

volumes:
    data_volume: