version: "3"

services:
    build:
        build: ./build
        volumes:
            - data_volume:/home/app
        depends_on:
            - build
            - db
    
    db:
        image: postgres:10
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            PGDATA: /var/lib/postgresql/data
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    web:
        image: tomcat:8.0
        ports:
            - "8080:8080"
        volumes:
            - data_volume:/usr/local/tomcat/webapps

volumes:
    data_volume: