version: '3'

services:
    db:
        image: mysql:5.7.5
        ports:
            - '3306:3306'
        expose:
            - '3306'
        environment:
            MYSQL_DATABASE: 'Appdb'
            MYSQL_USER: 'App'
            MYSQL_PASSWORD: 'Secret'
            MYSQL_ROOT_PASSWORD: 'App'
        volumes:
            - ./sqldata:/var/lib/mysql
        networks:
            net:
                ipv4_address: 192.168.0.11

    web:
        image: 'tomcat:8.0'
        ports:
            - '8080:8080'
        volumes:
            - data_volume:/usr/local/tomcat/webapps
        networks:
            net:
                ipv4_address: 192.168.0.12
        depends_on:
            - db           

    build:
        build: ./build
        volumes:
            - data_volume:/home/app
        networks:
            net:
                ipv4_address: 192.168.0.10       

volumes:
    data_volume:

networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24        